@host = localhost/liveticker
@keyword_cmp = competition
@user_name = temp_test_user
@user_password = temp_test_password

### 

// expect no errors

GET http://{{host}}/{{keyword_cmp}}.php

### 

// expecting PARAM_OUT_OF_RANGE (caused by method)
GET http://{{host}}/{{keyword_cmp}}.php
    ?method=hello

###

// expecting PARAM_OUT_OF_RANGE (caused by id < 1)
GET http://{{host}}/{{keyword_cmp}}.php
    ?id=0

###

// expecting NaN (caused by day)
GET http://{{host}}/{{keyword_cmp}}.php
    ?days=hello

###

// expecting NaN (caused by limit)
GET http://{{host}}/{{keyword_cmp}}.php
    ?limit=lovely

###

// expecting NaN (caused by id)
GET http://{{host}}/{{keyword_cmp}}.php
    ?id=world