@host = localhost/liveticker
@keyword_discipline = discipline
@user_name = temp_test_user
@user_password = temp_test_password

### 

// expect no errors
GET http://{{host}}/{{keyword_discipline}}.php
    ?competition=1

### 

// expecting MISSING_INFORMATION (competition id is missing)
GET http://{{host}}/{{keyword_discipline}}.php

###

// expecting MISSING_INFORMATION (competition id is NaN)
GET http://{{host}}/{{keyword_discipline}}.php
    ?competition=hello

###

// expecting PARAM_OUT_OF_RANGE (caused by id < 1)
GET http://{{host}}/{{keyword_discipline}}.php
    ?competition=0

###

// expecting no error and competitions with 
GET http://{{host}}/{{keyword_discipline}}.php
    ?days=hello

###

// expecting NaN (caused by limit)
GET http://{{host}}/{{keyword_discipline}}.php
    ?limit=lovely

###

// expecting NaN (caused by id)
GET http://{{host}}/{{keyword_discipline}}.php
    ?id=world